version: '3.8'
services:
  rovnomark:
    build: .
    container_name: rovnomark-app
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data  # База ляжет в /opt/rovnomark/data/
    restart: always