services:
  rovnomark:
    build: .
    container_name: rovnomark-app
    ports:
      - "8080:8080"
    volumes:
      # Папка ./data с хоста пробрасывается в рабочую папку приложения
      - ./data:/app/data
    restart: always