# docker-compose.yml
services:
  rovnomark:
    build: .
    container_name: rovnomark-app-test
    command: ["/bin/marking-service", "--port", "8000", "--debug"]
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./data:/app/data
      # МОНТИРУЕМ ПАПКУ ИНТЕРФЕЙСА:
      - ./ui2:/app/ui2
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}"
        max-size: "50m"
        max-file: "3"
